import { Header } from "@/components/header";
import { SanityLive } from "@/sanity/lib/live";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <section className="bg-white min-h-screen">
          <Header />
          {children}
          <SanityLive />
        </section>
      </body>
    </html>
  );
}
